on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
       - name: Setup Dependencies
       - uses: actions/checkout@v4 
       - uses: quarto-dev/quarto-actions/setup@v2
       - uses: r-lib/actions/setup-r@v2
         with:
          use-public-rspm: true
       - uses: r-lib/actions/setup-r-dependencies@v2
         with:
          extra-packages: 'any::pkgdown, local::.'
          needs: website
          
       - name: Publish to GitHub Pages (and render)
         uses: quarto-dev/quarto-actions/publish@v2
         with:
          target: gh-pages
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
